(function(jscl){
'use strict';
(function(values, internals){
//var l1=internals.make_lisp_string('loading repl-web/repl.lisp!');
//console.log(internals.xstring(l1));
var l2=internals.intern('%WRITE-STRING');
var l3=internals.intern('T','COMMON-LISP');
var l4=internals.intern('*ROOT*');
var l5=internals.make_lisp_string('jqconsole');
var l6=internals.intern('NIL','COMMON-LISP');
var l7=internals.make_lisp_string('jqconsole-output');
var l8=internals.make_lisp_string('');
var l9=internals.make_lisp_string('jqconsole');
var l10=internals.make_lisp_string('Write');
var l11=internals.make_lisp_string('console');
var l12=internals.make_lisp_string('log');
l2.fvalue=(function(){var FUNC=(function JSCL_USER_WRITESTRING(values,v1,v2){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v2=l3.value;
;
default:break;
}var v3=this;
return (function(){return internals.js_to_lisp((function(){var TMP=internals.symbolValue(l4)[internals.xstring(l5)];
return TMP===undefined?l6.value:TMP;
})())!==l6.value?internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l9)][internals.xstring(l10)](internals.lisp_to_js(v1),internals.lisp_to_js(l7),internals.lisp_to_js(l8),internals.lisp_to_js(v2))):internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l11)][internals.xstring(l12)](internals.lisp_to_js(v1)));
})();
});
FUNC.fname='%WRITE-STRING';
return FUNC;
})();
l2;
var l13=internals.intern('LOAD-HISTORY');
var l14=internals.make_lisp_string('jqhist');
var l15=internals.make_lisp_string('localStorage');
var l16=internals.make_lisp_string('getItem');
var l17=internals.make_lisp_string('JSON');
var l18=internals.make_lisp_string('parse');
var l19=internals.make_lisp_string('jqconsole');
var l20=internals.make_lisp_string('SetHistory');
l13.fvalue=(function(){var FUNC=(function JSCL_USER_LOADHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v5=this;
return (function(){return (function(v7){return (v7===null?l3.value:l6.value)!==l6.value?l6.value:internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l19)][internals.xstring(l20)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l17)][internals.xstring(l18)](internals.lisp_to_js(v7))))));
})(internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l15)][internals.xstring(l16)](internals.lisp_to_js(l14))));
})();
});
FUNC.fname='LOAD-HISTORY';
return FUNC;
})();
l13;
var l21=internals.intern('SAVE-HISTORY');
var l22=internals.make_lisp_string('jqhist');
var l23=internals.make_lisp_string('jqconsole');
var l24=internals.make_lisp_string('GetHistory');
var l25=internals.make_lisp_string('JSON');
var l26=internals.make_lisp_string('stringify');
var l27=internals.make_lisp_string('localStorage');
var l28=internals.make_lisp_string('setItem');
l21.fvalue=(function(){var FUNC=(function JSCL_USER_SAVEHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v8=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l27)][internals.xstring(l28)](internals.lisp_to_js(l22),internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l25)][internals.xstring(l26)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l23)][internals.xstring(l24)]())))))));
})();
});
FUNC.fname='SAVE-HISTORY';
return FUNC;
})();
l21;
var l29=internals.intern('%SEXPR-COMPLETE');
var l30=internals.intern('LENGTH','COMMON-LISP');
var l31=internals.intern('CHAR','COMMON-LISP');
var l32=internals.intern('EQL','COMMON-LISP');
l29.fvalue=(function(){var FUNC=(function JSCL_USER_SEXPRCOMPLETE(values,v10){internals.checkArgs(arguments.length-1,1);
var v11=this;
return (function(){return (function(v13,v14,v15,v16,v17){(function(){return (function(){while ((function(){var x1=v13;
if (typeof x1!='number') throw 'Not a number!';
var x2=v16;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l3.value:l6.value;
})()!==l6.value){if (v15!==l6.value) (function(v19){return l32.fvalue(internals.pv,v19,'\n')!==l6.value?(l6.value,v15=l6.value):l6.value;
})(l31.fvalue(internals.pv,v10,v13));
 else if (v14!==l6.value) (function(v20){return l32.fvalue(internals.pv,v20,'\\')!==l6.value?(l6.value,(function(){var v22=1;
var v23=(function(){var x1=v13;
if (typeof x1!='number') throw 'Not a number!';
var x2=v22;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v13=v23;
})()):l32.fvalue(internals.pv,v20,'"')!==l6.value?(l6.value,(v14=l6.value),(function(){var v25=1;
var v26=(function(){var x1=v17;
if (typeof x1!='number') throw 'Not a number!';
var x2=v25;
if (typeof x2!='number') throw 'Not a number!';
return x1-x2;
})();
return v17=v26;
})()):l6.value;
})(l31.fvalue(internals.pv,v10,v13));
 else (function(v27){return l32.fvalue(internals.pv,v27,';')!==l6.value?(l6.value,v15=l3.value):l32.fvalue(internals.pv,v27,'(')!==l6.value?(l6.value,v15!==l6.value?l6.value:(function(){var v29=1;
var v30=(function(){var x1=v17;
if (typeof x1!='number') throw 'Not a number!';
var x2=v29;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v17=v30;
})()):l32.fvalue(internals.pv,v27,')')!==l6.value?(l6.value,v15!==l6.value?l6.value:(function(){var v32=1;
var v33=(function(){var x1=v17;
if (typeof x1!='number') throw 'Not a number!';
var x2=v32;
if (typeof x2!='number') throw 'Not a number!';
return x1-x2;
})();
return v17=v33;
})()):l32.fvalue(internals.pv,v27,'"')!==l6.value?(l6.value,(function(){var v35=1;
var v36=(function(){var x1=v17;
if (typeof x1!='number') throw 'Not a number!';
var x2=v35;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v17=v36;
})(),v14=l3.value):l6.value;
})(l31.fvalue(internals.pv,v10,v13));
(function(){var v38=1;
var v39=(function(){var x1=v13;
if (typeof x1!='number') throw 'Not a number!';
var x2=v38;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v13=v39;
})();
}return l6.value;
})();
})();
return (function(){var x1=v17;
if (typeof x1!='number') throw 'Not a number!';
return x1<=0?l3.value:l6.value;
})()!==l6.value?l6.value:0;
})(0,l6.value,l6.value,l30.fvalue(internals.pv,v10),0);
})();
});
FUNC.fname='%SEXPR-COMPLETE';
return FUNC;
})();
l29;
var l33=internals.intern('TOPLEVEL');
var l34=internals.make_lisp_string('(');
var l35=internals.make_lisp_string(')');
var l36=internals.make_lisp_string('parents');
var l37=internals.make_lisp_string('jqconsole');
var l38=internals.make_lisp_string('RegisterMatching');
var l39=internals.make_lisp_string('~a> ');
var l40=internals.intern('*PACKAGE*','COMMON-LISP');
var l41=internals.intern('PACKAGE-NAME','COMMON-LISP');
var l42=internals.intern('FORMAT','COMMON-LISP');
var l43=internals.make_lisp_string('jqconsole-prompt');
var l44=internals.make_lisp_string('jqconsole');
var l45=internals.make_lisp_string('Write');
var l46=internals.make_lisp_string('console');
var l47=internals.make_lisp_string('log');
var l48=internals.make_lisp_string('message');
var l49=internals.make_lisp_string('ERROR[!]: ~a~%');
var l50=internals.make_lisp_string('jqconsole-error');
var l51=internals.make_lisp_string('jqconsole');
var l52=internals.make_lisp_string('Write');
var l53=internals.intern('*HANDLER-BINDINGS*');
var l54=internals.intern('ERROR','COMMON-LISP');
var l55=internals.make_lisp_string('message');
var l56=internals.intern('%ERROR');
var l57=internals.intern('READ-FROM-STRING','COMMON-LISP');
var l58=internals.intern('LIST','COMMON-LISP');
var l59=internals.intern('EVAL-INTERACTIVE');
var l60=internals.make_lisp_string('~S~%');
var l61=internals.make_lisp_string('jqconsole-return');
var l62=internals.make_lisp_string('jqconsole');
var l63=internals.make_lisp_string('Write');
var l64=internals.make_lisp_string('ERROR: ');
var l65=internals.make_lisp_string('jqconsole-error');
var l66=internals.make_lisp_string('jqconsole');
var l67=internals.make_lisp_string('Write');
var l68=internals.intern('!CONDITION-ARGS');
var l69=internals.make_lisp_string('jqconsole-error');
var l70=internals.make_lisp_string('jqconsole');
var l71=internals.make_lisp_string('Write');
var l72=internals.intern('STRING','COMMON-LISP');
var l73=internals.make_lisp_string('jqconsole-error');
var l74=internals.make_lisp_string('jqconsole');
var l75=internals.make_lisp_string('Write');
var l76=internals.make_lisp_string('jqconsole');
var l77=internals.make_lisp_string('Prompt');
l33.fvalue=(function(){var FUNC=(function JSCL_USER_TOPLEVEL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v40=this;
return (function(){internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l37)][internals.xstring(l38)](internals.lisp_to_js(l34),internals.lisp_to_js(l35),internals.lisp_to_js(l36)));
(function(v42){return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l44)][internals.xstring(l45)](internals.lisp_to_js(v42),internals.lisp_to_js(l43)));
})(l42.fvalue(internals.pv,l6.value,l39,l41.fvalue(internals.pv,internals.symbolValue(l40))));
return (function(v68){return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l76)][internals.xstring(l77)](internals.lisp_to_js(l3.value),internals.lisp_to_js(v68),internals.lisp_to_js(internals.symbolFunction(l29))));
})((function JSCL_USER_NIL(values,v43){internals.checkArgs(arguments.length-1,1);
var v44=this;
return (function(){(function(){try{return (function(){try{var v49=[];
return (function(v50){return (function(){var v51=1;
var v52=[];
TBLOOP:while (true){try{switch(v51){case 1:(function(v53){return internals.bindSpecialBindings([l53],[v53],(function(){(function(){var v55=new internals.Cons(l54,(function JSCL_USER_NIL(values,v56){internals.checkArgs(arguments.length-1,1);
var v57=this;
v50=v56;
return (function(){throw new internals.TagNLX(v52,2);
})();
}));
var v58=new internals.Cons(v55,internals.symbolValue(l53));
return l53.value=v58;
})();
return (function(){try{return (function(){throw new internals.BlockNLX(v49,(function(){var x1=l30.fvalue(internals.pv,v43);
if (typeof x1!='number') throw 'Not a number!';
return x1>0?l3.value:l6.value;
})()!==l6.value?(function(){var v62=l57.fvalue(internals.pv,v43);
var v63=(function(){var FUNC=internals.symbolFunction(l58);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l59.fvalue(values,v62);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
return (function(){return (function(v65,v66){(function(){while (v65!==l6.value){v66=internals.car(v65);
internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l62)][internals.xstring(l63)](internals.lisp_to_js(l42.fvalue(internals.pv,l6.value,l60,v66)),internals.lisp_to_js(l61)));
l6.value;
v65=internals.cdr(v65);
}return l6.value;
})();
return l6.value;
})(v63,l6.value);
})();
})():l6.value,'G320');
})();
}catch (v59){v59=internals.js_to_lisp(v59);
return (internals.isNLX(v59)?l3.value:l6.value)!==l6.value?(function(){throw v59;
})():l56.fvalue(internals.pv,(function(v60){return v60!==l6.value?v60:v59;
})(internals.js_to_lisp((function(){var TMP=v59[internals.xstring(l55)];
return TMP===undefined?l6.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l53));
case 2:(function(){throw new internals.BlockNLX(v49,(function(v67){internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l66)][internals.xstring(l67)](internals.lisp_to_js(l64),internals.lisp_to_js(l65)));
internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l70)][internals.xstring(l71)](internals.lisp_to_js((function(){var F=internals.symbolFunction(l42);
var ARGS=[internals.pv,l6.value];
var TAIL=l68.fvalue(internals.pv,v67);
while (TAIL!=l6.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})()),internals.lisp_to_js(l69)));
return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l74)][internals.xstring(l75)](internals.lisp_to_js(l72.fvalue(internals.pv,'\n')),internals.lisp_to_js(l73)));
})(v50),'G320');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v52) v51=JUMP.label;
 else throw JUMP;
}}return l6.value;
})();
})(l6.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v49) return CF.values;
 else throw CF;
}})();
}catch (v46){v46=internals.js_to_lisp(v46);
internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l46)][internals.xstring(l47)](internals.lisp_to_js(v46)));
return (function(v48){return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l51)][internals.xstring(l52)](internals.lisp_to_js(l42.fvalue(internals.pv,l6.value,l49,v48)),internals.lisp_to_js(l50)));
})((function(v47){return v47!==l6.value?v47:v46;
})(internals.js_to_lisp((function(){var TMP=v46[internals.xstring(l48)];
return TMP===undefined?l6.value:TMP;
})())));
}})();
l21.fvalue(internals.pv);
return l33.fvalue(values);
})();
}));
})();
});
FUNC.fname='TOPLEVEL';
return FUNC;
})();
l33;
var l78=internals.intern('WEB-INIT');
var l79=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l80=internals.intern('WRITE-FN','KEYWORD');
l80.value=l80;
var l81=internals.intern('MAKE-STREAM');
var l82=internals.intern('HTML','KEYWORD');
l82.value=l82;
//var l83=internals.intern('WELCOME-MESSAGE');
var l84=internals.make_lisp_string('load');
var l85=internals.make_lisp_string('window');
var l86=internals.make_lisp_string('addEventListener');
l78.fvalue=(function(){var FUNC=(function JSCL_USER_WEBINIT(values){internals.checkArgsAtMost(arguments.length-1,0);
var v69=this;
return (function(){l13.fvalue(internals.pv);
l79.value=l81.fvalue(internals.pv,l80.value,(function JSCL_USER_NIL(values,v71){internals.checkArgs(arguments.length-1,1);
var v72=this;
return l2.fvalue(values,v71);
}));
//l83.fvalue(internals.pv,l82.value,l3.value);
return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l85)][internals.xstring(l86)](internals.lisp_to_js(l84),internals.lisp_to_js((function JSCL_USER_NIL(values){var v75=l6.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v75=new internals.Cons(arguments[I+1],v75);
var v76=this;
return l33.fvalue(values);
}))));
})();
});
FUNC.fname='WEB-INIT';
return FUNC;
})();
l78;
l78.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
